#### 04. Autograd (자동미분)
- PyTorch는 Tensor의 모든 연산에 대해서 자동 미분이 가능함
- 자동미분은 역전파에 활용됨
- requires_grad: Tensor의 속성으로, True로 설정해야 자동미분이 가능
- tensor.backward(): 미분 실행
- tensor.grad: 미분값을 확인할 수 있는 속성

In [1]:
import torch

In [ ]:
x = torch.tensor([1.], requires_grad=True)
y = x ** 2
print(y)
print("미분 전: ", x.grad) # None


# backward()는 기본적으로 한 번만 쓰고 그래프를 버림
# 같은 그래프로 두 번째 역전파가 필요하면, y.backward(retain_graph=True)를 사용해야 함
y.backward(retain_graph=True)
print("미분 후: ", x.grad) # tensor([2.])

# x.grad.zero_(): 초기화 (초기화 하지 않으면 기본 누적됨)
x.grad.zero_()
z = 3 * y
print(z)

z.backward()
print("z 미분 후: ", x.grad) # RuntimeError  
print("z 미분 후: ", x.grad) # z 미분 후:  tensor([8.]) -> y.backward(retain_graph=True)
print("z 미분 후: ", x.grad) # z 미분 후:  tensor([6.]) -> x.grad.zero_()

tensor([1.], grad_fn=<PowBackward0>)
미분 전:  None
미분 후:  tensor([2.])
tensor([3.], grad_fn=<MulBackward0>)
z 미분 후:  tensor([6.])
z 미분 후:  tensor([6.])


In [ ]:
# 체인룰
x = torch.tensor([1.], requires_grad=True)
a = x ** 2
b = a + 1
c = b ** 2
c.backward()
print(x.grad) # tensor([8.])

# 이 텐서를 계산 그래프에서 분리
result = x.grad.detach()
print(result.requires_grad) # False
print(result.item()) # 8.0


tensor([8.])
False
8.0


In [ ]:
# 다변수 함수 미분
x = torch.tensor([1.], requires_grad=True)
y = torch.tensor([3.], requires_grad=True)
z = 2 * (x ** 2) + y ** 2
print(z)
z.backward()
print(x.grad) # tensor([4.])
print(y.grad) # tensor([6.])

tensor([11.], grad_fn=<AddBackward0>)
tensor([4.])
tensor([6.])


In [ ]:
# with torch.no_grad(): 
# grad_gn을 계산하고 싶지 않을 때 사용
# => 모델 훈련 후 test data를 가지고 평가할 때 사용

x = torch.tensor([1.], requires_grad=True)

with torch.no_grad():
    y = x ** 2
    print("with 안: ", x.requires_grad) # with 안:  True
    print(y) # tensor([1.])

print(x.requires_grad) # True
y = x ** 2
y.backward() # RuntimeError
y.backward() # True -> y = x ** 2

with 안:  True
tensor([1.])
True
